# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

# Spring Configuration
spring:

  output:
    ansi:
      enabled: always

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/drama_house
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
    change-log: classpath:master/changelog-master.xml
  servlet:
    multipart:
      max-file-size: 34343MB
      max-request-size: 34343MB
